apiVersion: kustomize.config.k8s.io/v1alpha1 # <-- Component notation
kind: Component

patches:
  - target:
      group: ""
      version: v1
      kind: Service
      name: nginx
    patch: |-
      - op: replace
        path: /spec/type
        value: NodePort
