apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../apps/nginx/base
  - ../../apps/nginx/ingress

components:
  - ../../patch/vpc-cni
  - ../../patch/direct-access-ingress
